# Generated by Django 5.0.2 on 2024-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
